services:
  nuxt:
    volumes:
      - ./nuxt:/app
      - nuxt_node_modules:/app/node_modules

  strapi:
    volumes:
      - ./strapi:/app
      - strapi_node_modules:/app/node_modules

  mmfs3:
    image: minio/minio:RELEASE.2023-10-25T06-33-25Z
    container_name: mmfs3
    restart: always
    environment:
      MINIO_ROOT_USER: ${S3_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET}
    ports:
      - '1003:1003'
      - '1004:1004'
    volumes:
      - ./minio-data:/data
    command: server --address ":1003" --console-address ":1004" /data

  createbucket:
    image: minio/mc:latest
    container_name: oneoffminio
    depends_on:
      - mmfs3
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set mmfs3 ${S3_ENDPOINT} ${S3_KEY} ${S3_SECRET};
      /usr/bin/mc mb mmfs3/${S3_BUCKET};
      /usr/bin/mc anonymous set public mmfs3/${S3_BUCKET};
      exit 0;"

volumes:
  nuxt_node_modules:
  strapi_node_modules:
