services:
  nuxt:
    build:
      context: ./nuxt
      dockerfile: Dockerfile
    env_file:
      - ./nuxt/.env
    environment:
      - PORT=${NUXT_PORT}
    volumes:
      - ./nuxt:/app
    ports:
      - "${NUXT_PORT}:${NUXT_PORT}"

  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    env_file:
      - ./strapi/.env
    environment:
      - PORT=${STRAPI_PORT}
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
    volumes:
      - ./strapi:/app
      - /app/node_modules
    ports:
      - "${STRAPI_PORT}:${STRAPI_PORT}"
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGPORT=${DATABASE_PORT}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
