services:
  nuxt:
    volumes:
      - ./nuxt:/app
      - /app/node_modules

  strapi:
    volumes:
      - ./strapi:/app
      - /app/node_modules

  mmfs3:
    image: minio/minio:RELEASE.2023-10-25T06-33-25Z
    container_name: mmfs3
    restart: always
    environment:
      MINIO_ROOT_USER: ${S3_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET}
    ports:
      - '9001:9001'
      - '9091:9091'
    volumes:
      - ./minio-data:/data
    command: server --address ":9001" --console-address ":9091" /data

  createbucket:
    image: minio/mc
    container_name: oneoffminio
    depends_on:
      - mmfs3
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set mmfs3 ${S3_ENDPOINT} ${S3_KEY} ${S3_SECRET};
      /usr/bin/mc mb mmfs3/${S3_BUCKET};
      /usr/bin/mc anonymous set public mmfs3/${S3_BUCKET};
      exit 0;"
