FROM --platform=linux/amd64 node:20-slim as builder
WORKDIR /app
COPY package*.json .
RUN npm ci && npm cache clean --force
COPY . .
RUN ["npm", "run", "build"]

FROM --platform=linux/amd64 node:20-slim as prod
WORKDIR /app
COPY --from=builder /app/.output /app/.output
CMD ["node", ".output/server/index.mjs"]
