on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string

jobs:
  build:
    outputs:
      # Manually specify the output image because steps.meta.outputs.tags is an array that includes ‘latest’.
      image: ghcr.io/${{ github.repository }}-${{ inputs.app }}:sha-${{ github.sha }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}-${{ inputs.app }}
          tags: | 
            type=sha,format=long
            type=raw,value=latest,enable={{is_default_branch}}
      - uses: docker/build-push-action@v6
        id: push
        with:
          context: ${{ inputs.app }}
          file: ${{ inputs.app }}/Dockerfile.prod
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.output.labels }}
          push: true
      - uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}-${{ inputs.app }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Store credentials
        run: doctl kubernetes cluster kubeconfig save nde

      - name: Update deployment
        run: |
          kubectl set image deployment/makemyflix-${{ inputs.app }} app=${{ needs.build.outputs.image }}

      - name: Verify deployment
        run: kubectl rollout status deployment/makemyflix-${{ inputs.app }} --timeout=120s
